---
# Common commands:
# pre-commit install
# pre-commit autoupdate
# pre-commit run --all-files --hook-stage push
#
# See https://pre-commit.com for more information
#  and https://pre-commit.com/hooks.html for more hooks

# Only commit is installed by default: https://pre-commit.com/#pre-commit-install
# Pending rename of pre-push from: https://github.com/pre-commit/pre-commit/issues/2732
default_install_hook_types: ["commit-msg", "pre-commit", "pre-push"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.7.0
    hooks:
      - id: commitizen
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies: ["mdformat-mkdocs[recommended]"]
        args: [--wrap=no]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        args: [--severity=warning]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        additional_dependencies:
          # Note: this version must be the same as the hook revision
          - "prettier@3.0.3"
          - "prettier-plugin-sh"
        types_or: [html, javascript, json, shell, yaml]
