# Site settings
title: The Bioengineering Life
email: king.kyle@ymail.com
description: "Making the future one step at a time #loftyGoals"
baseurl: ""
url: "http://KyleKing.github.io"
twitter_username: Kyle4Miles
github_username:  KyleKing

# Build settings
markdown: kramdown
permalink: pretty
