# Site settings
title: The Bioengineering Life
author: Kyle King
email: king.kyle@ymail.com
description: "Making the future one step at a time #loftyGoals"
baseurl: ""
url: "http://KyleKing.github.io"
twitter_username: Kyle4Miles
instagram_username: KyleLikesBikes #not configured
github_username:  KyleKing

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll Suported plugins: https://help.github.com/articles/using-jekyll-plugins-with-github-pages
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  # ---
  # redirect_from: "/foo"
  # ---
  - jekyll-mentions
  # Type @repositoryName inside content body
  - jemoji
