---
site_name: personal_site
site_author: Kyle King
site_description: personal_site project documentation
site_url: https://kyleking.me
repo_name: kyleking/personal_site
repo_url: https://github.com/kyleking/KyleKing.github.io
edit_uri: edit/main/docs
docs_dir: docs
site_dir: releases/site

theme:
  name: material
  palette:
    - scheme: default
      accent: green
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.autohide

watch:
  - personal_site

plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog
  - blog:
      # enabled: !ENV [CI, false]
      blog_toc: true
      blog_dir: "."
      post_date_format: long
      post_readtime: false
  - build_plantuml:
      render: server # or "local"
      bin_path: /usr/local/bin/plantuml # ignored when render: server
      server: http://www.plantuml.com/plantuml # official plantuml server
      output_format: svg
      diagram_root: docs/diagrams
      output_folder: out
      input_folder: src
      input_extensions: puml
  # # Don't generate code documentation
  # - gen-files:
  #     scripts:
  #       - docs-code/gen_ref_nav.py
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      strict: false
      type: date
  # # Don't generate code documentation
  # - literate-nav:
  #     nav_file: SUMMARY.md
  # FIXME: Try out Kroki instead of 'mkdocs-mermaid2-plugin'
  #   https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin
  # - mermaid2:
  #     version: 10.4.0 # https://github.com/mermaid-js/mermaid/releases
  # # Don't generate code documentation
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           docstring_section_style: spacy
  #           line_length: 120
  #           separate_signature: true
  #           show_category_heading: true
  - search
  - section-index
  - live-edit

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - def_list
  - extra
  - fenced_code
  - footnotes
  - markdown_captions
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite # Supports "mock shebangs": `!#js console.log('123');`
  - pymdownx.superfences
  #   # make exceptions to highlighting of code:
  #   custom_fences:
  #     - name: mermaid
  #       class: mermaid
  #       format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.keys # Instead of `<kbd>` surround with `++`
  # - pymdownx.magiclink:
  #   repo_url_shorthand: true
  #   user: kyleking
  #   repo: recipes
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - smarty
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 5
  # # https://github.com/squidfunk/mkdocs-material/blob/fb18b20695fd27e0a4351fb9597e7307241e2f15/mkdocs.yml
  # # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/?h=magiclink
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.tabbed:
  #     alternate_style: true
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde

extra_css:
  - _styles/extra.css
  - _styles/mkdocstrings.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _javascript/tables.js
