---
name: Update Docs

"on":
  push:
    branches: [main]
  workflow_dispatch: null # For manual runs

# Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  # Repository contents, commits, branches, downloads, releases, and merges.
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # For git-revision-date-localized-plugin

        # https://github.com/mkdocs/mkdocs/discussions/2369#discussioncomment-625475
      - name: Configure git user
        run: |-
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Build and deploy documentation
        run: TBD!
